---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(janitor)
```

```{r prepare_data, include=FALSE}
df <- read_csv("dataset/DataDNA Dataset Challenge -- January 2023.csv")

df <- clean_names(df)

df$caffeine_mg <- as.numeric(df$caffeine_mg)

df <- mutate_all(df, ~ifelse(is.na(.), 0, .))

df$size <- str_extract(df$beverage_prep, "^(Short|Tall|Grande|Venti|Solo|Doppio)")
df <- df %>% fill(size, .direction = "down")

df_scores <- df %>%  filter(size %in% c("Tall", "Solo", "Doppio"))

df_updated <- reactive({
  df_scores$score <- (
    df_scores$sugars_g * input$sugar
    + df_scores$calories
    + df_scores$total_fat_g
    + df_scores$sodium_mg
    + df_scores$total_carbohydrates_g
    + df_scores$cholesterol_mg
    + df_scores$protein_g
    + df_scores$caffeine_mg
  )
  
  df_scores[order(df_scores$score, decreasing = TRUE), ]
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r}
sliderInput("sugar", "Sugar:", 
            min = -1, max = 1, value = 0, step = 0.05, ticks = FALSE)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart B

```{r}
# renderTable({ head(df_updated(), 3)[c(1:3, 20)] })
renderTable({ df_updated()[1:3, c("beverage_category", "beverage", "beverage_prep", "score")] })
# renderPrint({ max(df_updated()$score) })
# renderPrint({ min(df_updated()$score) })
```

### Chart C

```{r}

```

